### PR TITLE
#163: replaces reboot styles with reset-css styles

### PR DESCRIPTION
**Pull request by janwidmer**
## Pull request
replaces reboot styles with reset-css styles
 
### Ticket
https://github.com/valantic/vue-template/issues/163
 
### Browser testing
- http://localhost:8080/styleguide
 
### Checklist
- [x] I merged the current development branch (before testing)
- [x] Added JSDoc and styleguide demo
- [x] Tested all links in project relevant browsers
- [x] Tested all links in different screen sizes
- [x] Did run automated tests and linters
- [x] Did assign ticket
- [x] Double checked target branch
 
## Review/Test checklist
- [ ] Did review code and documentation
- [ ] Tested all links in project relevant browsers
- [ ] Tested all links in different screen sizes
- [ ] Did check accessibility (Wave, only errors)
- [ ] Re-assign ticket to developer

### CODE REVIEW

**Comment by janwidmer** [comment]
How much should the styles previously being defined as part of the reboot be restored at other places?

**Comment by patric-eberle** [comment]
> How much should the styles previously being defined as part of the reboot be restored at other places?

@janwidmer sorry, I don't get that question. You mean what should be kept and what not, or what do want to know?

**Comment by janwidmer** [comment]
> > How much should the styles previously being defined as part of the reboot be restored at other places?
> 
> @janwidmer sorry, I don't get that question. You mean what should be kept and what not, or what do want to know?

Since the previous reboot styles where also containing some margins and so on, the current state probably does not look exactly like before.. should I invest time in that or are we just taking what there is now as base?

**Comment by claudio147** [comment]
- [ ] I get a few compile errors when I try to run `npm run dev:s`
- [ ] There is an issue with the math.div() 
image

- [ ] The icon of the styleguide menu is missing
image

ℹ️  I was not able to check the styleguidist because of the compile errors.

**Review by claudio147 — CHANGES_REQUESTED** [review]
See comment above

**Comment by janwidmer** [comment]
@claudio147 the menu button was broken on develop but already fixed. I merged develop in again, should work now. The warning  about `math.div()` is probably caused by the usage of a css var inside `math.div()` I have not found any solution to disable the warning..

**Review by claudio147 — APPROVED** [review]

**Pull request merged**
